### ISSUE TITLE
Use with default Prom Client registry?

### ISSUE THREAD

**Issue by robross0606** [thecodenebula/apollo-prometheus-plugin#11]
I'm unclear how to get this to work with the default global registry instead of having to create one.  Why is the registry parameter not optional?

**Comment by robross0606** [comment]
Even when creating a new `Registry()` I get the following exception when trying to use it with `prometheusPlugin()`.
```javascript
const { Registry } = require('prom-client')
const registry = new Registry()
const plugin = prometheusPlugin(registry, { enableNodeMetrics: true })
```

```
TypeError: registry.collectors is not a function
    at Object.collectDefaultMetrics (C:\Code\ncp\study-design-service\node_modules\@thecodenebula\apollo-prometheus-plugin\node_modules\prom-client\lib\defaultMetrics.js:45:4)
    at default_1 (C:\Code\ncp\study-design-service\node_modules\@thecodenebula\apollo-prometheus-plugin\dist\prometheus_plugin.js:8:23)
    at Object.<anonymous> (C:\Code\ncp\study-design-service\src\server.js:129:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Code\ncp\study-design-service\index.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:1060:14)
    at Object..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 
```

**Comment by robross0606** [comment]
I figured out the error part.  This plugin _only_ works with prom-client 12.0.0.  It won't work with 11.x and it won't work with 13.x either.
